"""Add user_id to Stroke model

Revision ID: 1cbe59b78e08
Revises: eb3851d81af4
Create Date: 2025-06-20 09:59:22.440016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cbe59b78e08'
down_revision = 'eb3851d81af4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('stroke', schema=None) as batch_op:
        # Adiciona a coluna permitindo nulos temporariamente
        batch_op.add_column(sa.Column('user_id', sa.String(length=255), nullable=True))

    # Pega a conexão para executar uma query
    bind = op.get_bind()
    session = sa.orm.Session(bind=bind)

    try:
        # Pega o primeiro usuário para usar como default.
        first_user = session.execute(sa.text("SELECT id FROM users ORDER BY id LIMIT 1")).fetchone()
        default_user_id = first_user[0] if first_user else None

        if default_user_id:
            # Atualiza todos os traços existentes com o ID do primeiro usuário
            op.execute(
                f"UPDATE stroke SET user_id = '{default_user_id}' WHERE user_id IS NULL"
            )
    finally:
        session.close()

    # Usa batch_alter_table para modificar a coluna e adicionar a chave estrangeira
    with op.batch_alter_table('stroke', schema=None) as batch_op:
        # Agora que os valores existentes estão preenchidos, altera a coluna para não nula
        batch_op.alter_column('user_id', existing_type=sa.String(length=255), nullable=False)
        # Cria a chave estrangeira
        batch_op.create_foreign_key('fk_stroke_user_id', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stroke', schema=None) as batch_op:
        batch_op.drop_constraint('fk_stroke_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')
    # ### end Alembic commands ###
