"""Adiciona suporte para usuários visitantes

Revision ID: eb3851d81af4
Revises: a6e6ff6eada7
Create Date: 2025-06-19 18:53:22.580884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb3851d81af4'
down_revision = 'a6e6ff6eada7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_guest', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_guest')

    # ### end Alembic commands ###
